// Code generated by MockGen. DO NOT EDIT.
// Source: subscription_confirms.go
//
// Generated by this command:
//
//	mockgen -source=subscription_confirms.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ananaslegend/reposeetory/internal/subscription/domain"
	subscription_confirms "github.com/ananaslegend/reposeetory/internal/subscription_confirms"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, p domain.CreateConfirmationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, p)
}

// GetConfirmationsWithLock mocks base method.
func (m *MockRepository) GetConfirmationsWithLock(ctx context.Context, limit int) ([]subscription_confirms.PendingConfirmation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmationsWithLock", ctx, limit)
	ret0, _ := ret[0].([]subscription_confirms.PendingConfirmation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirmationsWithLock indicates an expected call of GetConfirmationsWithLock.
func (mr *MockRepositoryMockRecorder) GetConfirmationsWithLock(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmationsWithLock", reflect.TypeOf((*MockRepository)(nil).GetConfirmationsWithLock), ctx, limit)
}

// GetByToken mocks base method.
func (m *MockRepository) GetByToken(ctx context.Context, token string) (*subscription_confirms.ConfirmRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*subscription_confirms.ConfirmRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockRepository)(nil).GetByToken), ctx, token)
}

// MarkConfirmed mocks base method.
func (m *MockRepository) MarkConfirmed(ctx context.Context, notifID int64, subscriptionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConfirmed", ctx, notifID, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConfirmed indicates an expected call of MarkConfirmed.
func (mr *MockRepositoryMockRecorder) MarkConfirmed(ctx, notifID, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConfirmed", reflect.TypeOf((*MockRepository)(nil).MarkConfirmed), ctx, notifID, subscriptionID)
}

// MarkSent mocks base method.
func (m *MockRepository) MarkSent(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockRepositoryMockRecorder) MarkSent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockRepository)(nil).MarkSent), ctx, id)
}

// MockMailSender is a mock of MailSender interface.
type MockMailSender struct {
	ctrl     *gomock.Controller
	recorder *MockMailSenderMockRecorder
	isgomock struct{}
}

// MockMailSenderMockRecorder is the mock recorder for MockMailSender.
type MockMailSenderMockRecorder struct {
	mock *MockMailSender
}

// NewMockMailSender creates a new mock instance.
func NewMockMailSender(ctrl *gomock.Controller) *MockMailSender {
	mock := &MockMailSender{ctrl: ctrl}
	mock.recorder = &MockMailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailSender) EXPECT() *MockMailSenderMockRecorder {
	return m.recorder
}

// SendConfirmation mocks base method.
func (m *MockMailSender) SendConfirmation(ctx context.Context, p domain.SendConfirmationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmation", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmation indicates an expected call of SendConfirmation.
func (mr *MockMailSenderMockRecorder) SendConfirmation(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmation", reflect.TypeOf((*MockMailSender)(nil).SendConfirmation), ctx, p)
}
