// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ananaslegend/reposeetory/internal/subscription/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockRepository) CreateSubscription(ctx context.Context, p domain.CreateSubscriptionParams) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, p)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockRepositoryMockRecorder) CreateSubscription(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockRepository)(nil).CreateSubscription), ctx, p)
}

// DeleteByUnsubscribeToken mocks base method.
func (m *MockRepository) DeleteByUnsubscribeToken(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUnsubscribeToken", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUnsubscribeToken indicates an expected call of DeleteByUnsubscribeToken.
func (mr *MockRepositoryMockRecorder) DeleteByUnsubscribeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUnsubscribeToken", reflect.TypeOf((*MockRepository)(nil).DeleteByUnsubscribeToken), ctx, token)
}

// ListByEmail mocks base method.
func (m *MockRepository) ListByEmail(ctx context.Context, email string) ([]domain.SubscriptionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEmail", ctx, email)
	ret0, _ := ret[0].([]domain.SubscriptionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEmail indicates an expected call of ListByEmail.
func (mr *MockRepositoryMockRecorder) ListByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEmail", reflect.TypeOf((*MockRepository)(nil).ListByEmail), ctx, email)
}

// UpsertRepo mocks base method.
func (m *MockRepository) UpsertRepo(ctx context.Context, p domain.UpsertRepoParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRepo", ctx, p)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRepo indicates an expected call of UpsertRepo.
func (mr *MockRepositoryMockRecorder) UpsertRepo(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRepo", reflect.TypeOf((*MockRepository)(nil).UpsertRepo), ctx, p)
}

// MockConfirmationCreator is a mock of ConfirmationCreator interface.
type MockConfirmationCreator struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmationCreatorMockRecorder
	isgomock struct{}
}

// MockConfirmationCreatorMockRecorder is the mock recorder for MockConfirmationCreator.
type MockConfirmationCreatorMockRecorder struct {
	mock *MockConfirmationCreator
}

// NewMockConfirmationCreator creates a new mock instance.
func NewMockConfirmationCreator(ctrl *gomock.Controller) *MockConfirmationCreator {
	mock := &MockConfirmationCreator{ctrl: ctrl}
	mock.recorder = &MockConfirmationCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmationCreator) EXPECT() *MockConfirmationCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConfirmationCreator) Create(ctx context.Context, p domain.CreateConfirmationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConfirmationCreatorMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfirmationCreator)(nil).Create), ctx, p)
}

// MockRemoteRepositoryProvider is a mock of RemoteRepositoryProvider interface.
type MockRemoteRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteRepositoryProviderMockRecorder
	isgomock struct{}
}

// MockRemoteRepositoryProviderMockRecorder is the mock recorder for MockRemoteRepositoryProvider.
type MockRemoteRepositoryProviderMockRecorder struct {
	mock *MockRemoteRepositoryProvider
}

// NewMockRemoteRepositoryProvider creates a new mock instance.
func NewMockRemoteRepositoryProvider(ctrl *gomock.Controller) *MockRemoteRepositoryProvider {
	mock := &MockRemoteRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockRemoteRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteRepositoryProvider) EXPECT() *MockRemoteRepositoryProviderMockRecorder {
	return m.recorder
}

// RepoExists mocks base method.
func (m *MockRemoteRepositoryProvider) RepoExists(ctx context.Context, p domain.RepoExistsParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoExists", ctx, p)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoExists indicates an expected call of RepoExists.
func (mr *MockRemoteRepositoryProviderMockRecorder) RepoExists(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoExists", reflect.TypeOf((*MockRemoteRepositoryProvider)(nil).RepoExists), ctx, p)
}
